# Generated by Django 3.2.16 on 2023-03-06 13:53

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import store.utils


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='related_words',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='http://localhost:9090/image.svg', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(default='http://localhost:9090/image.svg', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('uid', models.CharField(default=store.utils.generate_uid, editable=False, max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='base_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='store.baseproduct'),
            preserve_default=False,
        ),
    ]
