# Generated by Django 3.2.16 on 2023-03-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20230306_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=1, editable=False, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
