# Generated by Django 3.2.16 on 2023-03-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_shop_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(editable=False, max_length=300, unique=True),
        ),
    ]
