# Generated by Django 4.1.7 on 2023-03-08 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_seller_historicalseller_historicalcustomer_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='shop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.shop'),
        ),
    ]
