openapi: 3.0.0
# Added by API Auto Mocking Plugin
info:
  description: Torob2 Api
  version: "1.0.0"
  title: Torob2 Api
tags:
- name: "private"
  description: "برای سرویس های داخلی."
- name: "public"
  description: "برای سرویس های خارجی"

paths:
  /main_cateogry/list/:
    get:
      tags:
      - public
      summary: لیست دسته های مهم
      responses:
        '200':
          description: returns categories in page
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/categoryItem'
  /nested_categories/:
    get:
      parameters:
          - in: query
            name: base_category
            description: use to get child categories of given category
            required: false
            schema:
              type: string
              example: "mobile"
      tags:
      - public
      summary: دیشکنری دسته ها
      responses:
        '200':
          description: return nested categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/catl1'
  /product/create-or-update/:
    post:
      tags:
      - private
      summary: کرالرها از این اندپوینت جهت ذخیره اطلاعات محصولات در پایگاه داده استفاده میکنند.
      description: crawler use this api to update backend
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/productCreateItem'
      responses:
        '200':
          description: returns changed or created product UID
          content:
            application/json:
              schema:
                type: object
                properties:
                  uid:
                    description: a 12 digit unique identifier
                    type: string
                    example: qAzwSx3Ed6Yh
  /product/list/:
    get:
      tags:
      - public
      summary: لیست محصولات با قابلیت فیلتر با دسته، محدوده قیمت، وضعیت موجودی و مرتب سازی و pagination
      parameters:
        - in: query
          name: category_id
          description: use to filter products by category
          required: false
          schema:
            type: integer
            example: 1
        - in: query
          name: price__lt
          description: use to filter products by max price
          required: false
          schema:
            type: integer
            example: 100000
        - in: query
          name: price__gt
          description: use to filter products by min price
          required: false
          schema:
            type: integer
            example: 10000
        - in: query
          name: is_available
          description: use to filter products by availability
          required: false
          schema:
            type: boolean
            example: true
        - in: query
          name: sort
          description: use to sort products
          required: false
          schema:
            type: string
            enum: [price-, price, date_updated, date_updated-]
            default: date_updated-
        - in: query
          name: page
          description: page number
          required: false
          schema:
            type: integer
            default: 1
        - in: query
          name: size
          description: number of records per page
          required: false
          schema:
            type: integer
            default: 10

      responses:
        '200':
          description: returns filtered products in page
          content:
            application/json:
              schema:
                type: object
                properties:
                  next:
                    type: string
                    nullable: true
                    example: '/product/list?page=2&size=10'
                    description: next page url if exists
                  perv:
                    type: string
                    nullable: true
                    example: null
                    description: previous page url if exists
                  count:
                    type: integer
                    description: total number of products with the given filters
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/productListItem'
  /product/detail/id/:
    get:
      tags:
      - public
      responses:
        '200':
          description: returns filtered products in page
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    $ref: '#/components/schemas/productItem'
  /product/redirect/:
    get:
      tags:
      - public
      summary: جهت دریافت آدرس محصول در سایت فروشنده و انتقال کاربر به سایت فروشنده
      parameters:
        - in: query
          name: uid
          description: uid of the required product
          required: true
          schema:
            type: string
            example: qAzwSx3Ed6Yh
      responses:
        '200':
          description: returns the product url in shop
          content:
            application/json:
              schema:
                type: object
                properties:
                  product_url:
                    type: string
                    example: 'http://digikala.com/DKP-1213'
  /product/price-change/list/:
    get:
      tags:
      - public
      summary: لیست تغییرات قیمت محصول
      parameters:
        - in: query
          name: uid
          description: product uid
          required: true
          schema:
            type: string
            example: qAzwSx3Ed6Yh
      responses:
        '200':
          description: returns price change list
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        price:
                          type: integer
                          example: 10
                        date:
                          type: integer
                          example: 1678823495

components:
  schemas:
    categoryItem:
      type: object
      properties:
        id:
          example: 1
          type: integer
        name:
          type: string
          example: موبایل و تبلت

    catl1:
      type: object
      properties:
        name:
          example: 'موبایل و تلوزیون'
          type: string
        link:
          example: 'https://torobche.ir/product/list/?category=موبایل و تلوزیون'
          type: string
        children:
          type: array
          items:
            $ref: '#/components/schemas/catl2'

    catl2:
      type: object
      properties:
        name:
          example: 'موبایل'
          type: string
        link:
          example: 'https://torobche.ir/product/list/?category=موبایل'
          type: string
        children:
          type: array
          items:
            $ref: '#/components/schemas/catl3'

    catl3:
      type: object
      properties:
        link:
          example: 'https://torobche.ir/product/list/?category=آیفون'
          type: string
        name:
          example: 'موبایل آیفون'
          type: string

    productCreateItem:
      type: object
      properties:
        page_url:
          description: product url in shop
          type: string
          example: 'http://digikala.com/DKP-1213'
        image_url:
          description: image url in shop
          type: string
          example: 'http://digikala.com/image.jpg'
        shop_domain:
          type: string
          example: 'digikala.com'
        name:
          type: string
          example: موبایل آیفون xs max 64Gb
        price:
          type: integer
          example: 12000000
        is_available:
          type: boolean
          example: true
        features:
          type: string
          example: {'حافظه': '24 Gb'}

    productListItem:
      type: object
      properties:
        product_url:
          description: torob product more info url
          type: string
          example: '/product/detail/qAzwSx3Ed6Yh'
        product_image_url:
          description: torob product image url
          type: string
          example: '/product/redirect/?uid=qAzwSx3Ed6Yh'
        shop_count:
          type: integer
          example: 10
        name:
          type: string
          example: موبایل آیفون xs max 64Gb
        price:
          type: string
          example: 12,000,000 تومان
        is_available:
          type: boolean
          example: true
        updated:
          type: string
          example: 12 دقیقه پیش



    productItem:
      type: object
      properties:
        uid:
          description: a 12 digit unique identifier
          type: string
          example: qAzwSx3Ed6Yh
        product_price_list_url:
          type: string
          example: '/product/price-change/list/?uid=qAzwSx3Ed6Yh'
        product_image_url:
          type: string
          example: '/image/hewfjw.jpg'
        shops:
          type: array
          items:
            type: object
            properties:
              redirect_url:
                description: torob product more info url
                type: string
                example: '/product/redirect/?uid=qAzwSx3Ed6Yh'
              name:
                type: string
                example: دیجیکالا
              city:
                type: string
                example: تبریز
              price:
                type: string
                example: 13,000,000 تومان
        name:
          type: string
          example: موبایل آیفون xs max 64Gb
        price:
          type: string
          example: 12,000,000 تومان
        is_available:
          type: boolean
          example: true
        updated:
          type: string
          example: 12 دقیقه پیش
        features:
          type: array
          items:
            type: object
        
