FROM python:3.6

RUN apt-get update && apt-get install -y libpq-dev
WORKDIR /app

RUN python -m venv /venv
COPY requirements.txt /app/
RUN pip install -r requirements.txt
COPY . /app/

RUN DJANGO_SETTINGS_MODULE=tests.settings coverage run manage.py test
