version: '2'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    command: postgres
    ports:
      - "5432:5432"
    environment:
      - TZ=Asia/Tehran
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  elasticsearch:
    image: elasticsearch:7.14.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
      - TZ=Asia/Tehran
      - discovery.type=single-node
  project1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - elasticsearch
    env_file:
      - .env