# Generated by Django 4.1.7 on 2023-03-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('shop_domain', models.CharField(max_length=30)),
                ('shop_name', models.CharField(max_length=30)),
                ('total_count_crawled', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'crawl_log',
                'abstract': False,
            },
        ),
    ]
